### ISSUE TITLE
Are there open source code of the paper"Addressing Challenging Place Recognition Tasks using Generative Adversarial Networks"?

### ISSUE THREAD

**Issue by qcl1994** [ylatif/ylatif.github.io#2]
Hi,
I'm interested in this work, just want to ask the open source code of it. Thank u so much

**Comment by ylatif** [comment]
Sorry the source is not public at the moment. However, we plan to put it out very soon.

**Comment by qcl1994** [comment]
Thank u! I will pay close attention to this work.

**Comment by weiyunchen92** [comment]
@ylatif Hi, I'm also interesting about your paper "Addressing Challenging Place Recognition Tasks using Generative Adversarial Networks". Is it still possible to open source code? Thanks!
